[package]
name = "journal"
version.workspace = true
edition.workspace = true

[dependencies]
base64.workspace = true
chrono.workspace = true
errors.workspace = true
serde.workspace = true
sqlx.workspace = true
utils.workspace = true
uuid.workspace = true

[dev-dependencies]
db.workspace = true
errors.workspace = true
tokio.workspace = true
user.workspace = true
