[package]
name = "journal_json"
version.workspace = true
edition.workspace = true

[dependencies]
axum.workspace = true
chrono.workspace = true
db.workspace = true
errors.workspace = true
serde.workspace = true
tracing.workspace = true
utils.workspace = true
uuid.workspace = true
journal.workspace = true
