[package]
name = "user_json"
version.workspace = true
edition.workspace = true

[dependencies]
axum.workspace = true
axum-extra.workspace = true
db.workspace = true
errors.workspace = true
hex.workspace = true
rand.workspace = true
reqwest.workspace = true
serde.workspace = true
tracing.workspace = true
user.workspace = true
utils.workspace = true
