[package]
name = "user"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
argon2.workspace = true
chrono.workspace = true
errors.workspace = true
serde.workspace = true
sqlx.workspace = true
utils.workspace = true
uuid.workspace = true

[dev-dependencies]
db.workspace = true
errors.workspace = true
sqlx.workspace = true
tokio.workspace = true
