[package]
name = "user"
version.workspace = true
edition.workspace = true

[dependencies]
chrono.workspace = true
errors.workspace = true
serde.workspace = true
sqlx.workspace = true
uuid.workspace = true

[dev-dependencies]
db.workspace = true
errors.workspace = true
sqlx.workspace = true
tokio.workspace = true
